---
# tasks file for roles/osp-instance-delete
#TODO:  - name: Fetch Instance Info

- name: Gather instance information
  include: roles/osp-facts/tasks/main.yml

- name: Delete instances
  os_server:
    cloud: ospcloud
    name: "{{ item.name }}" 
    state: absent
  with_items: "{{result.ansible_facts.openstack_servers}}"
   
