- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{ osp_GUID }}.rhpds.opentlc.com"
       group: workstation


- hosts: workstation
#  remote_user: cloud-user
#  ssh_key_data:  "/root/.ssh/openstack.pem"
  become: yes
  roles:
    - osp-servers
